[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_WS_URL = "wss://lit-emergency-api.herokuapp.com/ws"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
